import { Download, Info, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useApp } from '../../app/AppContext'
import { EChart } from '../../components/EChart'
import type { BasePosition } from '../../types/domain'
const positions:BasePosition[]=['QB','RB','WR','TE','K','DST']
export function Analysis(){const {results,analyses}=useApp();const [position,setPosition]=useState<BasePosition>('RB');const [search,setSearch]=useState('');const [page,setPage]=useState(0);const metric=analyses.find(x=>x.position===position)!;const rows=useMemo(()=>results.filter(x=>x.position===position&&x.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.ppg-a.ppg),[results,position,search]);const visible=rows.slice(page*12,page*12+12)
 const chart={tooltip:{trigger:'axis'},grid:{left:45,right:20,top:20,bottom:30},xAxis:{type:'category',data:rows.slice(0,45).map(x=>x.rank)},yAxis:{type:'value',name:'PPG'},series:[{type:'line',smooth:true,showSymbol:false,data:rows.slice(0,45).map(x=>+x.ppg.toFixed(2)),lineStyle:{width:3,color:'#2fa69a'},areaStyle:{color:'rgba(47,166,154,.12)'},markLine:{symbol:'none',data:[{yAxis:metric.starterCutoff,name:'Starter cutoff'},{yAxis:metric.replacementPpg,name:'Replacement'}]}}]}
 const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));a.download=`fcc-${position.toLowerCase()}-analysis.json`;a.click();URL.revokeObjectURL(a.href)}
 return <><div className="page-heading compact"><div><span className="eyebrow">POSITION ANALYSIS</span><h1>Where value falls away</h1><p>Rankings, starter thresholds, and replacement value under your active rules.</p></div><button className="button" onClick={download}><Download size={16}/>Export JSON</button></div>
 <div className="position-tabs" role="tablist">{positions.map(p=><button className={p===position?'active':''} onClick={()=>{setPosition(p);setPage(0)}} key={p}>{p}</button>)}</div>
 <div className="stats-grid">{[['Qualified players',metric.distribution.count],['Starter cutoff',`${metric.starterCutoff.toFixed(1)} PPG`],['Replacement level',`${metric.replacementPpg.toFixed(1)} PPG`],['Top-to-replacement',`+${metric.topToReplacementGap.toFixed(1)} PPG`]].map(([a,b])=><div className="metric card" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div>
 <section className="card panel"><div className="panel-head"><div><span className="eyebrow">RANKED DROP-OFF</span><h2>{position} points per game</h2></div><span className="legend"><i/> Starter and replacement markers</span></div><EChart option={chart} summary={`${position} ranked drop-off. Starter cutoff ${metric.starterCutoff.toFixed(1)} and replacement ${metric.replacementPpg.toFixed(1)} points per game.`}/></section>
 <section className="card table-panel"><div className="panel-head"><div><span className="eyebrow">PLAYER RESULTS</span><h2>{position} rankings</h2></div><label className="search"><Search size={16}/><input aria-label="Search players" placeholder="Search players" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label></div><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Player</th><th>Team</th><th>Games</th><th>Total</th><th>PPG</th><th>Status</th><th>VOR</th><th>σ</th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td>{x.rank}</td><td><b>{x.name}</b></td><td>{x.team}</td><td>{x.games}</td><td>{x.total.toFixed(1)}</td><td><b>{x.ppg.toFixed(1)}</b></td><td><span className={x.flex?'badge flex':x.starter?'badge starter':'badge'}>{x.flex?'FLEX':x.starter?'STARTER':'BENCH'}</span></td><td className={x.replacementValue>=0?'positive':''}>{x.replacementValue>=0?'+':''}{x.replacementValue.toFixed(1)}</td><td>{x.standardDeviation.toFixed(1)}</td></tr>)}</tbody></table></div><div className="pagination"><span>{rows.length} players</span><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><b>{page+1} / {Math.max(1,Math.ceil(rows.length/12))}</b><button disabled={(page+1)*12>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>
 <div className="info-note"><Info/><p><b>How thresholds work:</b> Base starters fill first at each position. FLEX then takes the best remaining RB, WR, or TE without selecting anyone twice. Replacement is the highest available non-starter.</p></div></>
}
