import { ArrowRight, BarChart3, Gauge, Settings2, Sparkles } from 'lucide-react'
import { Link } from 'react-router'
import { useApp } from '../../app/AppContext'
import { localRepository } from '../../repositories/local'
import { EChart } from '../../components/EChart'
export function Dashboard(){const {config,analyses,score}=useApp();const scarcity=[...analyses].sort((a,b)=>b.topToReplacementGap-a.topToReplacementGap)[0];const volatile=[...analyses].sort((a,b)=>b.distribution.coefficientOfVariation-a.distribution.coefficientOfVariation)[0]
 const option={tooltip:{trigger:'axis'},grid:{left:38,right:12,top:15,bottom:28},xAxis:{type:'category',data:analyses.map(x=>x.position)},yAxis:{type:'value'},series:[{type:'bar',data:analyses.map(x=>+x.meanStarterVor.toFixed(1)),itemStyle:{color:'#2fa69a',borderRadius:[5,5,0,0]}}]}
 return <><div className="page-heading"><div><span className="eyebrow">COMMISSIONER LAB</span><h1>League balance, made measurable.</h1><p>Test roster and scoring choices against player performance before your league votes.</p></div><Link className="button primary" to="/builder"><Settings2 size={17}/>Edit configuration</Link></div>
 <section className="score-hero card"><div className="score-ring" style={{'--score':`${score*3.6}deg`} as React.CSSProperties}><strong>{score.toFixed(0)}</strong><span>/ 100</span></div><div><span className="eyebrow">MODEL-BASED BALANCE SCORE</span><h2>{score>70?'Strong positional balance':'Opportunity to rebalance'}</h2><p>Positions contribute meaningfully without one group overwhelming starter value. This is a comparison tool—not an objective measure of fun.</p><Link to="/methodology">How this is calculated <ArrowRight size={14}/></Link></div><div className="mini-stats"><div><small>Most scarce</small><b>{scarcity.position}</b><span>{scarcity.topToReplacementGap.toFixed(1)} PPG gap</span></div><div><small>Most volatile</small><b>{volatile.position}</b><span>{volatile.distribution.standardDeviation.toFixed(1)} σ</span></div></div></section>
 <div className="stats-grid">{[['League size',`${config.roster.teams} teams`],['Weekly starters',`${config.roster.teams*(config.roster.QB+config.roster.RB+config.roster.WR+config.roster.TE+config.roster.FLEX+config.roster.K+config.roster.DST)}`],['Qualified players',`${analyses.reduce((n,x)=>n+x.distribution.count,0)}`],['Scoring profile','Half PPR']].map(([a,b])=><div className="metric card" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div>
 <div className="two-col"><section className="card panel"><div className="panel-head"><div><span className="eyebrow">POSITION VALUE</span><h2>Mean starter VOR</h2></div><Link to="/analysis">Full analysis</Link></div><EChart option={option} summary="Bar chart comparing mean starter value over replacement by position."/></section>
 <section className="card panel"><span className="eyebrow">QUICK ACTIONS</span><h2>Keep exploring</h2><div className="quick-list"><Link to="/analysis"><BarChart3/><span><b>Analyze positions</b><small>See drop-off and replacement value</small></span><ArrowRight/></Link><Link to="/optimizer"><Gauge/><span><b>Optimize scoring rules</b><small>Run transparent candidate search</small></span><ArrowRight/></Link><Link to="/saved"><Sparkles/><span><b>Saved work</b><small>{localRepository.saved().length} configurations stored locally</small></span><ArrowRight/></Link></div></section></div></>
}
