import { Copy, RotateCcw, Save } from 'lucide-react'
import { useNavigate } from 'react-router'
import { useApp } from '../../app/AppContext'
import type { LeagueConfiguration, RosterSettings } from '../../types/domain'
const rosterKeys=['QB','RB','WR','TE','FLEX','K','DST','bench','ir'] as const
const scoringFields=[['passingTouchdown','Pass TD'],['interception','Interception'],['passingYard','Pass yard'],['rushingYard','Rush yard'],['receivingYard','Receiving yard'],['reception','Reception'],['teReceptionPremium','TE premium'],['fumbleLost','Fumble lost']] as const
export function Builder(){const {config,setConfig,save,reset}=useApp();const nav=useNavigate();const patch=(p:Partial<LeagueConfiguration>)=>setConfig({...config,...p,updatedAt:new Date().toISOString()})
 const changeRoster=(key:keyof RosterSettings,val:number)=>patch({roster:{...config.roster,[key]:Math.max(0,val)}})
 return <><div className="page-heading compact"><div><span className="eyebrow">LEAGUE CONFIGURATION</span><h1>Build your scoring environment</h1><p>Every change updates starter demand and analysis immediately.</p></div><div className="actions"><button className="button" onClick={reset}><RotateCcw size={16}/>Reset</button><button className="button primary" onClick={save}><Save size={16}/>Save locally</button></div></div>
 <div className="builder-layout"><div>
 <section className="card form-section"><div className="section-title"><span>01</span><div><h2>General settings</h2><p>Name this experiment and choose its data season.</p></div></div><div className="form-grid"><label className="wide">Configuration name<input value={config.name} onChange={e=>patch({name:e.target.value})}/></label><label>Season<select value={config.season} onChange={e=>patch({season:+e.target.value})}><option value="2026">2026 · Demo</option></select></label><label>League size<input type="number" min="4" max="32" value={config.roster.teams} onChange={e=>changeRoster('teams',+e.target.value)}/></label><label className="wide">Description<textarea value={config.description} onChange={e=>patch({description:e.target.value})}/></label></div></section>
 <section className="card form-section"><div className="section-title"><span>02</span><div><h2>Starting roster</h2><p>Flex is allocated from the best remaining RB, WR, or TE.</p></div></div><div className="step-grid">{rosterKeys.map(k=><div className="stepper" key={k}><label>{k.toUpperCase()}</label><button onClick={()=>changeRoster(k,config.roster[k]-1)} aria-label={`Decrease ${k}`}>−</button><b>{config.roster[k]}</b><button onClick={()=>changeRoster(k,config.roster[k]+1)} aria-label={`Increase ${k}`}>+</button></div>)}</div></section>
 <section className="card form-section"><div className="section-title"><span>03</span><div><h2>Offensive scoring</h2><p>Points per event. Negative values apply penalties.</p></div></div><div className="form-grid">{scoringFields.map(([k,label])=><label key={k}>{label}<input type="number" step=".01" value={config.scoring.offense[k]} onChange={e=>patch({scoring:{...config.scoring,offense:{...config.scoring.offense,[k]:+e.target.value}}})}/></label>)}</div></section>
 </div><aside className="builder-summary card"><span className="eyebrow">LIVE DEMAND</span><h2>{config.roster.teams} team league</h2>{rosterKeys.slice(0,7).map(k=><div key={k}><span>{k} starters</span><b>{config.roster[k]*config.roster.teams}</b></div>)}<hr/><p><b>{config.roster.FLEX*config.roster.teams} flex jobs</b> will go to the highest-scoring remaining RBs, WRs, and TEs after base slots fill.</p><button className="button primary full" onClick={()=>nav('/analysis')}>Continue to analysis</button><button className="button full" onClick={()=>patch({...config,id:crypto.randomUUID(),name:`${config.name} copy`,createdAt:new Date().toISOString()})}><Copy size={16}/>Duplicate</button></aside></div></>
}
