import { Check, Gauge, Play, Save, WandSparkles } from 'lucide-react'
import { useState } from 'react'
import { useApp } from '../../app/AppContext'
import { localRepository } from '../../repositories/local'
import { optimize } from '../../services/optimizer'
import type { OptimizationResult } from '../../types/domain'
export function Optimizer(){const {config,setConfig,results}=useApp();const [size,setSize]=useState<250|1000|5000>(250);const [result,setResult]=useState<OptimizationResult|null>(null);const [running,setRunning]=useState(false)
 const run=()=>{setRunning(true);setTimeout(()=>{setResult(optimize(config,results,size,42));setRunning(false)},50)}
 const apply=()=>{if(!result)return;setConfig({...config,id:crypto.randomUUID(),name:`${config.name} · Optimized`,scoring:result.best.scoring,updatedAt:new Date().toISOString(),createdAt:new Date().toISOString()})}
 const save=()=>{if(result)localRepository.saveRun({...result,id:crypto.randomUUID(),configurationName:config.name})}
 return <><div className="page-heading compact"><div><span className="eyebrow">TRANSPARENT RULE OPTIMIZER</span><h1>Search for a better balance</h1><p>A deterministic random search compares understandable rule sets—this is optimization, not AI.</p></div></div>
 <div className="optimizer-grid"><section className="card form-section"><div className="section-title"><span><Gauge/></span><div><h2>Run settings</h2><p>Candidate rules are scored using positional balance, depth, volatility, and simplicity.</p></div></div><label>Search depth<select value={size} onChange={e=>setSize(+e.target.value as 250|1000|5000)}><option value="250">Quick · 250 candidates</option><option value="1000">Standard · 1,000 candidates</option><option value="5000">Deep · 5,000 candidates</option></select></label><div className="weight-list">{['Positional balance','Starter depth','Replacement availability','Weekly competitiveness','Controlled volatility','Scoring simplicity'].map((x,i)=><div key={x}><span>{x}</span><div><i style={{width:`${[90,72,68,60,55,70][i]}%`}}/></div></div>)}</div><button className="button primary full" onClick={run} disabled={running}><Play size={17}/>{running?'Evaluating candidates…':`Run ${size.toLocaleString()} candidates`}</button></section>
 <section className="card result-card">{!result?<div className="empty"><WandSparkles/><h2>Ready to optimize</h2><p>Run the engine to compare your baseline with transparent scoring recommendations.</p></div>:<><span className="eyebrow">BEST RECOMMENDATION</span><div className="comparison-score"><div><small>Baseline</small><strong>{result.baselineScore.toFixed(0)}</strong></div><span>→</span><div className="best"><small>Recommended</small><strong>{result.best.score.toFixed(0)}</strong></div></div><h2>Human-readable rule changes</h2><div className="rule-changes">{[['Pass TD',config.scoring.offense.passingTouchdown,result.best.scoring.offense.passingTouchdown],['Interception',config.scoring.offense.interception,result.best.scoring.offense.interception],['Reception',config.scoring.offense.reception,result.best.scoring.offense.reception],['TE premium',config.scoring.offense.teReceptionPremium,result.best.scoring.offense.teReceptionPremium]].map(([label,a,b])=><div key={label}><span>{label}</span><b>{a} → {b}</b></div>)}</div><ul className="reason-list">{result.best.explanation.map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="actions"><button className="button primary" onClick={apply}>Apply to new config</button><button className="button" onClick={save}><Save size={16}/>Save run</button></div></>}</section></div></>
}
